### ISSUE TITLE
Excited about this! please put some readme for details

### ISSUE THREAD

**Issue by aahnik** [oprypin/markdown-callouts#1]
...

**Comment by oprypin** [comment]
Sorry, can't believe it's been two weeks, and I still don't have a README!

I'll just ... share some common examples.

Check out [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) on this page (**the content of the page itself is not relevant here**):
https://oprypin.github.io/mkdocs-literate-nav/
They look completely normal, but the syntax to write them is much simpler.

Check out the source code *and* the fact that it doesn't look totally weird on GitHub (`!!!`)
https://github.com/oprypin/mkdocs-literate-nav#readme
https://raw.githubusercontent.com/oprypin/mkdocs-literate-nav/master/README.md

The 4 keywords used there are `IMPORTANT:` `TIP:` `INFO:` `NOTE:` -- <kbd>Ctrl</kbd>+<kbd>F</kbd> search for them in the source and compare to the page.

**Comment by aahnik** [comment]
Yup, I understand this problem and that's why I got interested in this project. A readme with instructions on how to use this would be really helpful.

**Comment by aahnik** [comment]
How to use this with mkdocs?

**Comment by oprypin** [comment]
Install it and add to markdown_extensions
https://github.com/oprypin/mkdocs-literate-nav/blob/5f8de18621614a86a2a9d79ad8bd53ba22118582/mkdocs.yml#L25
