### ISSUE TITLE
Support Note and Warning blockquote as hint container

### ISSUE THREAD

**Issue by jcwangxp** [oprypin/markdown-callouts#16]
Would you like to support following github markdown style for mkdocs, and it'll be perfect.

> **Note**
> Some text here

> **Note**: Some text here

> **Note**: Some text here
> Addtional Content

> **Warning**
> Some text here

> **Warning**: Some text here

> **Warning**: Some text here
> Addtional Content

```
> **Note**
> Some text here

> **Note**: Some text here

> **Note**: Some text here
> Addtional Content

> **Warning**
> Some text here

> **Warning**: Some text here

> **Warning**: Some text here
> Addtional Content
```

**Comment by oprypin** [comment]
Yes, I want to support it. Haven't gotten around to it 😕

**Comment by oprypin** [comment]
I started a pull request to support it. It works, maybe only documentation is left

**Comment by oprypin** [comment]
It is interesting - none of your blockquotes show up correctly decorated as a callout anymore. What's the actual syntax these days?

**Comment by oprypin** [comment]
Interesting - I think GitHub ended up going with the Obsidian syntax instead, and **dropping this other syntax entirely**

https://github.com/orgs/community/discussions/16925



> ## Update - 14 November 2023
> 
>   * **Add support for `[!TIP]` and `[!CAUTION]`.**
> 
>   * Add support for alerts in Markdown files on [GitHub Mobile](https://github.com/mobile) apps. (pending a mobile app update)
> 
>   * Add support for various Markdown extensions such as Math rendering, relative links, task lists, animated image player and footnotes.
> 
>   * Prevent alerts from being nested within other elements.
> 
>   * **The initial syntax using e.g. `**Note**` isn't supported any longer.**
> 
>

**Comment by oprypin** [comment]
OK so this syntax isn't actually used anywhere anymore, so it's pointless to add support for it
