### ISSUE TITLE
Allow more than one word for the title

### ISSUE THREAD

**Issue by froschdesign** [oprypin/markdown-callouts#3]
## Current behaviour

At the moment the syntax is limited to one word for the title:

> The syntax is: as the start of a paragraph, write a word in all capital letters, followed by a colon and a space

https://oprypin.github.io/markdown-callouts/#usage

https://github.com/oprypin/markdown-callouts/blob/cea02a93c837e92d8a67ac694779c34742002db7/markdown_callouts/__init__.py#L11

## Feature request

It would be great if two or more words were allowed, e.g.

```markdown
INSTALLATION REQUIREMENTS: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
massa, nec semper lorem quam in massa.
```

## Use case

Our use case: https://docs.laminas.dev/laminas-i18n/translation/#translation

```markdown
> INSTALLATION REQUIREMENTS: The translation support of laminas-i18n depends on the
> [laminas-servicemanager](https://docs.laminas.dev/laminas-servicemanager/) component,
> so be sure to have it installed before getting started:
>
> ```bash
> $ composer require laminas/laminas-servicemanager
> ```
```

**Comment by oprypin** [comment]
Thanks for writing the request.

Unrelated: how did you discover this project?

**Comment by oprypin** [comment]
Ah and just to make sure you're aware. The "admonition" extension itself can still serve your needs well. (and it is *not* tied to mkdocs-material). "markdown-callouts" project is just if you don't like its syntax.

https://oprypin.github.io/markdown-callouts/#custom-titles

> ### Custom titles
> 
> Not supported at the moment, mainly because the syntax choice for it can be controversial. Currently the title of the admonition will always be the titular word of the callout as written. If you need a custom title, you can still use the *[admonition][]*   extension alongside.

[admonition]: https://python-markdown.github.io/extensions/admonition/
