### ISSUE TITLE
Allow arbitrary titles independent of the admonition class

### ISSUE THREAD

**Issue by oprypin** [oprypin/markdown-callouts#4]
Presently, we have just this:

```markdown
NOTE: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
massa, nec semper lorem quam in massa.
```

![image](https://user-images.githubusercontent.com/371383/137458437-320398a9-e642-4a7f-8cdb-cd8ae77dd38f.png)

We need to come up with a syntax to be able to set a fully custom title, like this:

![image](https://user-images.githubusercontent.com/371383/137458369-638c41a6-bb3f-4375-bf0d-144e434b9db8.png)

Some ideas:

1. ```markdown
   NOTE: **This is used as the title.** Lorem ipsum dolor sit amet, consectetur
   adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non
   consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.
   ```
   (thanks @pawamoy)

2. ```markdown
   NOTE "This is used as the title": Lorem ipsum dolor sit amet, consectetur
   adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non
   consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.
   ```

3. ```markdown
   NOTE (This is used as the title): Lorem ipsum dolor sit amet, consectetur
   adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non
   consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.
   ```

For reference/inspiration: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

**Comment by froschdesign** [comment]
@pawamoy 

This gives us many advantages:

- custom title
- custom markup for the title
- custom markup for the body without limitations (like before)
- and easy implementation

Great idea! 👍

**Comment by oprypin** [comment]
>     NOTE - This is used as the title: Lorem ipsum dolor sit amet, consectetur
>     adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non
>     consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.

@pawamoy 
I like that direction of thinking.

But I have found a possibly fatal flaw...
It is not possible to have a "colon: something else" in the title :confounded: 

```
NOTE - Spider-Man: The Movie: Lorem ipsum dolor sit amet, consectetur
```
???

> allows custom markup in both the title and the body.

Now *that* may actually be hard to implement :sweat_smile:

**Comment by oprypin** [comment]
Though, to be fair, there hasn't been any style suggested where that looks good. Perhaps you'd drop the extraneous "Warning:" and rely on just the icon from admonitions styling

**Comment by froschdesign** [comment]
The question is if you really have to break the borders of the simple idea of this extension? Do we really need a title that is completely customisable?

**Comment by pawamoy** [comment]
It's true that with `NOTE - Title: Contents` you can't include `:` in the title. But any other solution would suffer from a similar issue: no double-quotes with `Note "Title": Contents`, or parentheses with `Note (Title): Contents`, unless you start counting opening and closing quotes/brackets, or add escaping support, etc.

I think that as long as the limitations are well documented, it*s fine :slightly_smiling_face:

**Comment by pawamoy** [comment]
Ah, I see. Why would the dot be undesired? A title is still a sentence, no?

**Comment by oprypin** [comment]
> I'm curious, I think you have a good view on Python-Markdown: how would that be easier than parsing the solution with quotes instead, for example? Would you be able to know that the next "inline" (after the matched NOTE) is a bold-formatted sentence or something?

So yes, the basic implementation is really easy as I imagined. See https://github.com/oprypin/markdown-callouts/pull/5. But that ease also comes with an issue - it would be hard to introduce the custom escapes that I envisioned, whether it is `\*` or `\.` or whatever.

**Comment by oprypin** [comment]
Ha! Nevermind on the difficulty of escapes. python-markdown puts escaped characters into htmlStash, so actually they are impossible for my extension to see, in a way that happens to be exactly right.

So this worked without me doing anything, as a way to preserve the dot in the output title:

```markdown
NOTE: **This is used as the title\.** Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non
consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.
```

**Comment by oprypin** [comment]
As for utilizing newlines, here's what I implemented there:

```markdown
NOTE: **Title**  
Lorem ipsum dolor sit amet,

NOTE: **Title.** Lorem ipsum dolor sit amet,

NOTE:
**Not a title.**  
Lorem ipsum dolor sit amet,
```

**Comment by pawamoy** [comment]
Nice! However, since we can use a line break with two trailing spaces instead of a dot, could we have an option to always preserve the trailing dot? :blush:

**Comment by oprypin** [comment]
I personally would never use that option (really don't like fiddling with trailing spaces) but seems no reason to not implement it as a config. Will do.

**Comment by pawamoy** [comment]
Thanks a lot. I myself often use sentences for titles (with a trailing dot), that's why I'm asking :slightly_smiling_face: 
Can't wait to migrate from admonitions to callouts!

**Comment by oprypin** [comment]
PR #5 is fully ready now. I'll probably release all that in the next 2 days.
