### ISSUE TITLE
Allow collapsible admonition blocks - <details>

### ISSUE THREAD

**Issue by oprypin** [oprypin/markdown-callouts#9]
Need to come up with some syntax to implement the equivalent of https://facelessuser.github.io/pymdown-extensions/extensions/details/#syntax

If the base syntax for callouts is this:

```markdown
> NOTE: **This is used as the title.** Lorem ipsum dolor sit amet, consectetur
> adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non
> consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.
```

How can we expand it to instead denote an initially closed `<details>` block and an initially open one?

![image](https://user-images.githubusercontent.com/371383/150436622-9cdb67c5-6f7c-4fe0-968c-d8339d641fae.png)

Maybe this? I... really don't know.

```markdown
>? NOTE: **Closed details.** Lorem ipsum dolor sit amet, consectetur

>! NOTE: **Open details.** Lorem ipsum dolor sit amet, consectetur
```

Fallback look:

<table><tr><td>

>? NOTE: **Closed details.** Lorem ipsum dolor sit amet, consectetur

>! NOTE: **Open details.** Lorem ipsum dolor sit amet, consectetur

</td></tr></table>

**Comment by pawamoy** [comment]
Can Python Markdown extensions parse HTML comments? If so, HTML comments could be used to add metadata. This would degrade perfectly :blush:

**Comment by oprypin** [comment]
I intend to move forward with the syntax I mentioned. The implementation looks easy.

I am not willing to go for HTML comments, somehow that feels like a step too far.

**Comment by oprypin** [comment]
cc @squidfunk @facelessuser

**Comment by facelessuser** [comment]
It doesn't really matter to me which way callouts go for collapsible blocks as long as it doesn't conflict with existing, popular extensions.  As you are aware, we are working towards a generic block syntax, but that shouldn't affect your decision to head in whatever path you choose.

I see nothing inherently wrong with the direction posted above.

**Comment by oprypin** [comment]
Right. I want to advertise this admonition syntax regardless of the generic block syntax, particularly for users who will have no other use for the generic block syntax other than admonitions.

**Comment by facelessuser** [comment]
No that's fine, I just saw you pinged me.
